## The functions below provide the capability to compute and store
## the inverse of a matrix. They assume that the matrix provided is
## invertible. If the matrix is not the cacheSolve function will 
## throw an error. The purpose of this is to minimize the number of
## times an inverse is calculated for a particular matrix. This may
## be beneficial since for very large matrices, calculating the 
## inverse can be a time consuming process.
## The makeCacheMatrix function builds a list of functions that 
## provide the necessary access to the actual matrix and its 
## stored inverse. Whenever the matrix values change, which must be
## done through the set function, it resets the stored inverse since
## it is no longer guaranteed to be the same. 
## The cacheSolve function takes as input the result of the 
## makeCacheMatrix function and returns the inverse of the matrix
## (if it exists).
## If the inverse of that matrix has already been calculated it 
## would be stored and can be retrieved by the get_inverse function.
## If the inverse had not already been calculated the current stored
## inverse would be NULL so the solve function would be used on the
## matrix to find the inverse. Therefore the solve function would
## only be used if the inverse hadn't already been found once.    

## makeCacheMatrix function builds the list of functions that can 
## retrieve and update the matrix and its inverse. This list acts as
## a special matrix object that can be used in the following 
## cacheSolve function

makeCacheMatrix <- function(x = matrix()) {
	
	cached_inverse <- NULL

	set <- function(new_matrix) {
		x <<- new_matrix
		cached_inverse <<- NULL
	}
	
	get <- function() {
		return(x)
	}

	set_inverse <- function(calculated_inverse) {
		cached_inverse <<- calculated_inverse
	}

	get_inverse <- function() {
		return(cached_inverse)
	}

	list(set = set, 
		get = get,
		set_inverse = set_inverse,
		get_inverse = get_inverse)
}


## cacheColve function returns the inverse of a matrix contained in
## the special matrix object generated by the makeCacheMatrix 
## function above. 

cacheSolve <- function(x, ...) {

	cached_inverse <- x$get_inverse()
	
	if(is.null(cached_inverse)) {
		print("Calculating Inverse")
		calculated_inverse <- solve(x$get(), ...)
		x$set_inverse(calculated_inverse)
		cached_inverse <- x$get_inverse()
	}	

	cached_inverse	
}




##Testing Commmands##
##cache_matrix <- makeCacheMatrix(x = matrix(c(3,4,1,2,7,9,1,0,2),nrow=3,ncol=3))
##print(cache_matrix$get())
##print(cache_matrix$get_inverse())
##print(cacheSolve(cache_matrix))
##print(cache_matrix$get_inverse())
##print(cacheSolve(cache_matrix))
##cache_matrix$set(matrix(c(3,4,1,6,7,9,1,0,2),nrow=3,ncol=3))
##print(cache_matrix$get())
##print(cache_matrix$get_inverse())
##print(cacheSolve(cache_matrix))
##print(cache_matrix$get_inverse())
##print(cacheSolve(cache_matrix))
